package template

import (
	"fmt"
	"strings"
	"sync"
	"time"
)

// HookContext provides context for generation hooks
type HookContext struct {
	TemplateName string
	Template     string
	Data         any
	Output       string
	Metadata     map[string]any
	IsPreHook    bool
}

// GenerationHook is a function that can modify template data or output
type GenerationHook func(ctx *HookContext) error

type PreHook func(ctx *HookContext) error // modify Data or Metadata
type PostHook func(ctx *HookContext) (string, error)

type HookManager struct {
	mu        sync.RWMutex
	preHooks  []PreHook
	postHooks []PostHook
}

func NewHooksManager() *HookManager {
	return &HookManager{
		preHooks:  make([]PreHook, 0),
		postHooks: make([]PostHook, 0),
	}
}

// AddPreHook registers a pre generation hook
func (e *HookManager) AddPreHook(hook PreHook) {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.preHooks = append(e.preHooks, hook)
}

// AddPostHook registers a post generation hook
func (e *HookManager) AddPostHook(hook PostHook) {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.postHooks = append(e.postHooks, hook)
}

func (e *HookManager) PreHooks() []PreHook {
	e.mu.RLock()
	defer e.mu.RUnlock()
	out := make([]PreHook, len(e.preHooks))
	copy(out, e.preHooks)
	return out
}

func (e *HookManager) PostHooks() []PostHook {
	e.mu.RLock()
	defer e.mu.RUnlock()
	out := make([]PostHook, len(e.postHooks))
	copy(out, e.postHooks)
	return out
}

////////////////////////////////////////////////////////////////////////////////

// CommonHooks provides a collection of commonly used hooks
type CommonHooks struct{}

// NewCommonHooks creates a new instance of CommonHooks
func NewCommonHooks() *CommonHooks {
	return &CommonHooks{}
}

// AddTimestampHook adds a timestamp to generated files
func (h *CommonHooks) AddTimestampHook() PostHook {
	return func(ctx *HookContext) (string, error) {
		timestamp := time.Now().Format("2006-01-02 15:04:05")
		header := fmt.Sprintf("// Generated on %s\n", timestamp)

		// Only add to Go files
		if isGoFile(ctx.TemplateName, ctx.Output) {
			return header + ctx.Output, nil
		}
		return ctx.Output, nil
	}
}

// AddCopyrightHook adds a copyright header
func (h *CommonHooks) AddCopyrightHook(copyright string) PostHook {
	return func(ctx *HookContext) (string, error) {
		if copyright == "" {
			return ctx.Output, nil
		}

		header := fmt.Sprintf("// %s\n", copyright)

		// Only add to code files
		if isCodeFile(ctx.TemplateName, ctx.Output) {
			return header + ctx.Output, nil
		}
		return ctx.Output, nil
	}
}

// AddLicenseHook adds a license header
func (h *CommonHooks) AddLicenseHook(license string) PostHook {
	return func(ctx *HookContext) (string, error) {
		if license == "" {
			return ctx.Output, nil
		}

		// Format license as comment block
		lines := strings.Split(license, "\n")
		var header strings.Builder
		header.WriteString("/*\n")
		for _, line := range lines {
			if line != "" {
				header.WriteString(" * ")
				header.WriteString(line)
			}
			header.WriteString("\n")
		}
		header.WriteString(" */\n\n")

		// Only add to code files
		if isCodeFile(ctx.TemplateName, ctx.Output) {
			return header.String() + ctx.Output, nil
		}
		return ctx.Output, nil
	}
}

// AddGeneratedWarningHook adds a warning that the file is generated
func (h *CommonHooks) AddGeneratedWarningHook() PostHook {
	return func(ctx *HookContext) (string, error) {
		warning := "// Code generated by go-template. DO NOT EDIT.\n"

		// Only add to Go files
		if isGoFile(ctx.TemplateName, ctx.Output) {
			return warning + ctx.Output, nil
		}
		return ctx.Output, nil
	}
}

// RemoveTrailingWhitespaceHook removes trailing whitespace from lines
func (h *CommonHooks) RemoveTrailingWhitespaceHook() PostHook {
	return func(ctx *HookContext) (string, error) {
		lines := strings.Split(ctx.Output, "\n")
		for i, line := range lines {
			lines[i] = strings.TrimRight(line, " \t")
		}
		return strings.Join(lines, "\n"), nil
	}
}

// AddMetadataHook adds template metadata for tracking
// By default, template_content is only populated by RenderString
func (h *CommonHooks) AddMetadataHook() PreHook {
	return func(ctx *HookContext) error {
		ctx.Metadata["processed_at"] = time.Now()
		ctx.Metadata["template_name"] = ctx.TemplateName
		ctx.Metadata["template_content"] = ctx.Template
		return nil
	}
}

// ValidateDataHook validates required data fields
func (h *CommonHooks) ValidateDataHook(requiredFields []string) PreHook {
	return func(ctx *HookContext) error {
		data, ok := ctx.Data.(map[string]any)
		if !ok {
			newData, err := convertToContext(data)
			if err != nil {
				return fmt.Errorf("unable to coerce data to map: %w", err)
			}
			data = newData
		}

		for _, field := range requiredFields {
			if _, exists := data[field]; !exists {
				return fmt.Errorf("required field '%s' is missing", field)
			}
		}
		return nil
	}
}

// SetDefaultsHook sets default values for missing data fields
func (h *CommonHooks) SetDefaultsHook(defaults map[string]any) PreHook {
	return func(ctx *HookContext) error {
		data, ok := ctx.Data.(map[string]any)
		if !ok {
			// Convert to map if it's not already
			data, err := convertToContext(data)
			if err != nil {
				return fmt.Errorf("unable to coerce data to map: %w", err)
			}
			ctx.Data = data
		}

		for key, value := range defaults {
			if _, exists := data[key]; !exists {
				data[key] = value
			}
		}
		return nil
	}
}

// Helper functions

// isGoFile checks if the output is for a Go file
func isGoFile(templateName, output string) bool {
	return strings.HasSuffix(templateName, ".go") ||
		strings.HasSuffix(templateName, ".go.tpl") ||
		strings.Contains(output, "package ")
}

// isCodeFile checks if the output is for a code file
func isCodeFile(templateName, output string) bool {
	// Check common code file extensions
	codeExtensions := []string{".go", ".js", ".ts", ".py", ".java", ".c", ".cpp", ".h", ".hpp"}
	for _, ext := range codeExtensions {
		if strings.HasSuffix(templateName, ext) || strings.HasSuffix(templateName, ext+".tpl") {
			return true
		}
	}

	// Check for common code patterns in output
	codePatterns := []string{"package ", "import ", "func ", "class ", "def ", "#include"}
	for _, pattern := range codePatterns {
		if strings.Contains(output, pattern) {
			return true
		}
	}

	return false
}
